# Specify output directory
outdir: /vast/palmer/scratch/olfson/im433/prs_test2/new_data/output/sanger_ocd_prscs_ancestry

# Location of this config file
config_file: /vast/palmer/scratch/olfson/im433/prs_test2/new_input/config.yaml

# Specify location of gwas_list file
gwas_list: /vast/palmer/scratch/olfson/im433/prs_test2/new_input/gwas_list.txt

# Specify location of target_list file
target_list: /vast/palmer/scratch/olfson/im433/prs_test2/new_input/target_list.txt

# Specify location of score_list file
score_list: NA

# Specify pgs_methods ('ptclump','dbslmm','prscs','sbayesr','lassosum','ldpred2','megaprs')
pgs_methods: ['prscs']

# Specify if you want test mode. Set to NA if you don't want test mode
testing: NA

# Specify number of cores for polygenic scoring methods (ptclump always uses 1)
cores_prep_pgs: 5

# Specify number of cores for target scoring
cores_target_pgs: 1

# Specify memory in megabytes for target scoring
mem_target_pgs: 2000

ancestry_prob_thresh: 0.3

resdir: /home/eh566/palmer_scratch/anx/wgs/prs/test/genopred_resources
